export const Routes = {
  AppLinks: 'AppLinks',
  Home: 'Home',
  HomeHooks: 'HomeHooks',
  Messages: 'Messages',
  MessagesHooks: 'MessagesHooks',
  Login: 'Login',
  LoginHooks: 'LoginHooks',
  RangeCounter: 'RangeCounter',
  RangeCounterHooks: 'RangeCounterHooks',
  ProductItemCount: 'ProductItemCount',
  ProductItemCountHooks: 'ProductItemCountHooks',
  ProductPriceValue: 'ProductPriceValue',
  ProductPriceValueHooks: 'ProductPriceValueHooks',
};
